Shop bán xe hơi/TrietTT_PC06359_Assignment_gd2/TrietTT_PC06359_Assignment/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrietTT_PC06359_Assignment.Data;
using TrietTT_PC06359_Assignment.Models;

namespace TrietTT_PC06359_Assignment.Controllers
{
    public class OrderController : Controller
    {
        private readonly ApplicationDBContext _db;
        public OrderController(ApplicationDBContext db)
        {
            _db = db;
        }
        public IActionResult Order()
        {
            List<Orders> orders = new List<Orders>();
            return View(orders);
        }
        public IActionResult OrderDetails (int id)
        {
            List<OrderDetails> orderDetails = _db.OrderDetails.Where(a => a.OrderID == id).Include(b => b.Orders).ToList();
            return View(orderDetails);
        }
    }
}

Shop bán xe hơi/TrietTT_PC06359_Assignment_gd2/TrietTT_PC06359_Assignment/Controllers/ProductController.cs
using TrietTT_PC06359_Assignment.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrietTT_PC06359_Assignment.Models;
using TrietTT_PC06359_Assignment.Data;

namespace TrietTT_PC06359_Assignment.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDBContext _dbcontex;
        public ProductController(ApplicationDBContext db)
        {

            _dbcontex = db;
        }
        public IActionResult Prod()
        {
            List<Cars> cars = _dbcontex.Cars.Include(c => c.Categories).ToList();
            return View(cars);
        }
        public IActionResult Prod_details (int id)
        {
            List<Cars> cars = _dbcontex.Cars.Include(c => c.Categories).ToList();

            cars = _dbcontex.Cars.Where(x => x.CarID == id).ToList();
            return View(cars);
        }
    }
}

Shop bán xe hơi/TrietTT_PC06359_Assignment_gd2/TrietTT_PC06359_Assignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TrietTT_PC06359_Assignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TrietTT_PC06359_Assignment.styles.css" asp-append-version="true" />
</head>
<body>
       <nav class="navbar navbar-expand-lg navbar-dark bg-dark">  
           <div class="container-fluid">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"/>
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
              <i class="bi bi-house"></i>Trang chủ
              </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbarScroll">
              <ul
                class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll"
                style="--bs-scroll-height: 100px"
              >
                <li class="nav-item">
                  <a class="nav-link " aria-current="page" asp-area="" asp-controller="Home" asp-action="About">
                    <i class="bi bi-list-task"></i> Giới thiệu</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " aria-current="page" asp-area="" asp-controller="Home" asp-action="Contact"
                    ><i class="bi bi-telephone"></i> Liên hệ</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " aria-current="page" asp-area="" asp-controller="Product" asp-action="Prod"
                    ><i class="bi bi-shop"></i> Sản phẩm</a>
                </li><li class="nav-item">
                  <a class="nav-link " aria-current="page" asp-area="" asp-controller="Order" asp-action="Order" 
                    ><i class="bi bi-cart"></i>Đơn hàng</a>
                </li>
              </ul>
              <ul class="nav dropdown navbar-nav navbar-right pe-5" >
                  <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                    Tài khoản
                  </a>
                  <ul class="dropdown-menu dropdown-menu-lg-end">
                    <li><a asp-area="" asp-controller="Home" asp-action="Login" class="dropdown-item">Đăng nhập</a></li>
                  </ul>
              </ul>
            </div>
          </div>
      </nav>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; 2024 - TrietTT_PC06359_Assignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>