Shop bán xe hơi/TrietTT_PC06359_Assignment_gd2/TrietTT_PC06359_Assignment/Models/Orders.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace TrietTT_PC06359_Assignment.Models
{
    public class Orders
    {
        [Key]
        public int OrderID { get; set; }

        [ForeignKey("Customers")]
        public int CustomerID { get; set; }

        [ForeignKey("Cars")]
        public int CarID { get; set; }

        public DateTime NgayDat { get; set; }
        public Customers? Customers { get; set; }
        public Cars? Cars { get; set; }
        public ICollection<OrderDetails> OrderDetails { get; set; }
    }
}

Shop bán xe hơi/TrietTT_PC06359_Assignment_gd2/TrietTT_PC06359_Assignment/Areas/User/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrietTT_PC06359_Assignment.Data;
using TrietTT_PC06359_Assignment.Models;

namespace TrietTT_PC06359_Assignment.Areas.User.Controllers
{
    [Area("User")]
    public class OrderController : Controller
    {
        public readonly ApplicationDBContext _db;
        public OrderController(ApplicationDBContext db)
        {
            _db = db;
        }
        public IActionResult Order(int id)
        {
            //int customerId = HttpContext.Session.GetInt32("CustomerId") ?? default(int);

            List<Orders> orders = _db.Orders.Where(x => x.CustomerID == id).Include(b => b.Customers).Include(a=> a.Cars).Include(c => c.Cars.Categories).ToList();
            return View(orders);
        }
        public IActionResult OrderDetails (int id)
        {
            List<OrderDetails> orderDetails = _db.OrderDetails.Where(a => a.OrderID == id).Include(b => b.Orders).ToList();
            return View(orderDetails);
        }
    }
}

Shop bán xe hơi/TrietTT_PC06359_Assignment_gd2/TrietTT_PC06359_Assignment/Areas/User/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrietTT_PC06359_Assignment.Data;
using TrietTT_PC06359_Assignment.Models;

namespace TrietTT_PC06359_Assignment.Areas.User.Controllers
{
    [Area("User")]
    public class OrdersController : Controller
    {
        private readonly ApplicationDBContext _context;

        public OrdersController(ApplicationDBContext context)
        {
            _context = context;
        }

        // GET: User/Orders
        public async Task<IActionResult> Index()
        {
            List<Cars> cars = _context.Cars.Include(o => o.Categories).ToList();
            return View(cars);
        }

        // GET: User/Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders
                .Include(o => o.Cars)
                .Include(o => o.Customers)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }

        // GET: User/Orders/Create
        public IActionResult Create()
        {
            ViewData["CarID"] = new SelectList(_context.Cars, "CarID", "CarID");
            ViewData["CustomerID"] = new SelectList(_context.Customers, "CustomerID", "CustomerID");
            return View();
        }

        // POST: User/Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderID,CustomerID,CarID,NgayDat")] Orders orders)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orders);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarID"] = new SelectList(_context.Cars, "CarID", "CarID", orders.CarID);
            ViewData["CustomerID"] = new SelectList(_context.Customers, "CustomerID", "CustomerID", orders.CustomerID);
            return View(orders);
        }

        // GET: User/Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders.FindAsync(id);
            if (orders == null)
            {
                return NotFound();
            }
            ViewData["CarID"] = new SelectList(_context.Cars, "CarID", "CarID", orders.CarID);
            ViewData["CustomerID"] = new SelectList(_context.Customers, "CustomerID", "CustomerID", orders.CustomerID);
            return View(orders);
        }

        // POST: User/Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderID,CustomerID,CarID,NgayDat")] Orders orders)
        {
            if (id != orders.OrderID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orders);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrdersExists(orders.OrderID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarID"] = new SelectList(_context.Cars, "CarID", "CarID", orders.CarID);
            ViewData["CustomerID"] = new SelectList(_context.Customers, "CustomerID", "CustomerID", orders.CustomerID);
            return View(orders);
        }

        // GET: User/Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders
                .Include(o => o.Cars)
                .Include(o => o.Customers)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }

        // POST: User/Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'ApplicationDBContext.Orders'  is null.");
            }
            var orders = await _context.Orders.FindAsync(id);
            if (orders != null)
            {
                _context.Orders.Remove(orders);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrdersExists(int id)
        {
          return (_context.Orders?.Any(e => e.OrderID == id)).GetValueOrDefault();
        }
    }
}

Shop bán xe hơi/TrietTT_PC06359_Assignment_gd2/TrietTT_PC06359_Assignment/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrietTT_PC06359_Assignment.Data;
using TrietTT_PC06359_Assignment.Models;

namespace TrietTT_PC06359_Assignment.Controllers
{
    public class OrderController : Controller
    {
        private readonly ApplicationDBContext _db;
        public OrderController(ApplicationDBContext db)
        {
            _db = db;
        }
        public IActionResult Order()
        {
            List<Orders> orders = new List<Orders>();
            return View(orders);
        }
        public IActionResult OrderDetails (int id)
        {
            List<OrderDetails> orderDetails = _db.OrderDetails.Where(a => a.OrderID == id).Include(b => b.Orders).ToList();
            return View(orderDetails);
        }
    }
}

Shop bán xe hơi/TrietTT_PC06359_Assignment_gd2/TrietTT_PC06359_Assignment/Controllers/PayController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrietTT_PC06359_Assignment.Data;
using TrietTT_PC06359_Assignment.Migrations;
using TrietTT_PC06359_Assignment.Models;

namespace TrietTT_PC06359_Assignment.Controllers
{
    public class PayController : Controller
    {
        private readonly ApplicationDBContext _dbcontex;
        public PayController(ApplicationDBContext db)
        {
            _dbcontex = db;
        }
        public IActionResult Pay_view(int id)
        {
            var cars = _dbcontex.Cars.Where(x => x.CarID == id).Include(x => x.Categories).ToList();
            return View(cars);
        }

        //     [HttpPost]
        // public IActionResult Pay_view(Orders model, string paymentMethod, int id)
        // {
        //     // Lấy thông tin từ form và tạo hóa đơn mới
        //     var order = new Orders
        //     {
        //         CarID = model.CarID,
        //         CustomerID = model.CustomerID,
        //         NgayDat = DateTime.Now // Hoặc thời gian khác tùy thuộc vào yêu cầu của bạn
        //     };

        //     _dbcontex.Orders.Add(order);
        //     _dbcontex.SaveChanges();

        //     // Tạo các chi tiết hóa đơn tương ứng
        //     var orderDetail = new OrderDetails
        //     {
        //         OrderID = order.OrderID,
        //         NgayTao = DateTime.Now, // Hoặc thời gian khác
        //         TongGia = order.Cars.Gia,
        //SoLuong = 1,
        //         TinhTrangThanhToan = paymentMethod// Lấy thông tin từ form
        //     };

        //     _dbcontex.OrderDetails.Add(orderDetail);
        //     _dbcontex.SaveChanges();

        //var cars = _dbcontex.Cars.Where(x => x.CarID == id).Include(x => x.Categories).ToList();
        //         //return View(cars);
        //         return RedirectToAction("Index", "Home"); // Hoặc trả về view hoặc redirect đến trang khác
        //     }
        // }
    }
}

Shop bán xe hơi/TrietTT_PC06359_Assignment_gd2/TrietTT_PC06359_Assignment/Areas/User/Views/Orders/Create.cshtml
@model TrietTT_PC06359_Assignment.Models.Orders

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Orders</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerID" class="control-label"></label>
                <select asp-for="CustomerID" class ="form-control" asp-items="ViewBag.CustomerID"></select>
            </div>
            <div class="form-group">
                <label asp-for="CarID" class="control-label"></label>
                <select asp-for="CarID" class ="form-control" asp-items="ViewBag.CarID"></select>
            </div>
            <div class="form-group">
                <label asp-for="NgayDat" class="control-label"></label>
                <input asp-for="NgayDat" class="form-control" />
                <span asp-validation-for="NgayDat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Shop bán xe hơi/TrietTT_PC06359_Assignment_gd2/TrietTT_PC06359_Assignment/Areas/User/Views/Orders/Delete.cshtml
@model TrietTT_PC06359_Assignment.Models.Orders

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Orders</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgayDat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgayDat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customers)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customers.CustomerID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cars)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cars.CarID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Shop bán xe hơi/TrietTT_PC06359_Assignment_gd2/TrietTT_PC06359_Assignment/Areas/User/Views/Orders/Details.cshtml
@model TrietTT_PC06359_Assignment.Models.Orders

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Orders</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgayDat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgayDat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customers)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customers.CustomerID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cars)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cars.CarID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.OrderID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Shop bán xe hơi/TrietTT_PC06359_Assignment_gd2/TrietTT_PC06359_Assignment/Areas/User/Views/Orders/Edit.cshtml
@model TrietTT_PC06359_Assignment.Models.Orders

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Orders</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderID" />
            <div class="form-group">
                <label asp-for="CustomerID" class="control-label"></label>
                <select asp-for="CustomerID" class="form-control" asp-items="ViewBag.CustomerID"></select>
                <span asp-validation-for="CustomerID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarID" class="control-label"></label>
                <select asp-for="CarID" class="form-control" asp-items="ViewBag.CarID"></select>
                <span asp-validation-for="CarID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayDat" class="control-label"></label>
                <input asp-for="NgayDat" class="form-control" />
                <span asp-validation-for="NgayDat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Shop bán xe hơi/TrietTT_PC06359_Assignment_gd2/TrietTT_PC06359_Assignment/Areas/User/Views/Orders/Index.cshtml
@model IEnumerable<TrietTT_PC06359_Assignment.Models.Cars>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    @* <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NgayDat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customers)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cars)
            </th>
            <th></th>
        </tr>
    </thead> *@
    <tbody>
@foreach (var item in Model) {
                <div class="row g-0 p-2">

                        <img class="col-md-4 img-thumbnail rounded p-2" src="\Image\Car\@item.HinhAnh">
                        <ul class="col-md-7 offset-md-1 p-2 card-body">
                            <li>Tên xe: @item.Ten</li>
                            <li>Mô tả: @item.MoTa</li>
                            <li>Đơn giá: @item.Gia</li>
                            <li>Loại: @item.Categories.TenLoai</li>
                            <li>Tình Trạng: @item.TinhTrang</li>
                            <li>Số lượng còn <span class="badge bg-warning">@item.SoLuongTon</span> chiếc</li>
                            <li>Năm sản xuất: @item.NamSanXuat</li>
                        </ul>
                </div>
                <div class="text-end m-2">
                     <a asp-area="User" asp-route-id="@item.CarID" asp-controller="Pay" asp-action="Pay_view" class="btn btn-warning btn-lg ms-3">Mua</a>
                </div>
                   
        @* <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NgayDat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customers.CustomerID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cars.CarID)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.OrderID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.OrderID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.OrderID">Delete</a>
            </td>
        </tr> *@
}
    </tbody>
</table>